apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gogs
  name: gogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  template:
    metadata:
      labels:
        app: gogs
    spec:
      containers:
      - image: docker.io/gogs/gogs
        name: gogs

