apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgress
  name: postgress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgress
  template:
    metadata:
      labels:
        app: postgress
    spec:
      containers:
      - image: postgress
        name: postgress
        env:
         - name: POSTGRESS_PASSWORD
           value: simplilearn
         - name: POSTGRESS_DB
           value: database1 
        

